### ISSUE TITLE
[feature request] Life Crystals on new floor instead?

### ISSUE THREAD

**Issue by noawx** [AquSG/TerRoguelike#10]
Currently when you get to a new floor it increases your Max HP by 20.

But could it be made so it gives a Life Crystal instead? This way you can see your health bar get bigger as you progress the floors.

The items would stay the same.

Might make a PR if i find the time.

**Comment by AquSG** [comment]
No. Life Crystals are pretty restrictive. Having it add to lifemax2 gives a lot more control over variables, also no other max life thing in the mod increases the heart count either, because that's not how Terraria works. It would be weird that only the built in health ups increase the size of your healthbar.

**Comment by noawx** [comment]
Ok that makes sense 👍
