### ISSUE TITLE
frequent crashes

### ISSUE THREAD

**Issue by beastup7up** [AquSG/TerRoguelike#11]
around every 3 rooms (including the item trading room, ) upon going through the portal to the next area I get a crash along with a message saying that Images\tiles_650 failed to load. the only mod installed at the time of getting the message was terroguelike. I have no active antivirus, I have tried uninstalling and re-installing the mod, restarting my computer, and just playing the game again to see if it was a one-off thing. I have experienced this crash 5 times now.
![Screenshot_20240722_150506](https://github.com/user-attachments/assets/630de7d2-17ea-4e5d-8bcb-d2873d7d7e30)

**Comment by beastup7up** [comment]
forgot to mention, this bug happens both when the option to load the entire world  are turned on and off.I cannot find the file that it says to share when asking for help because i cannot make the window bigger. i will try to look but no promises.

**Comment by beastup7up** [comment]
I think I found the file needed to share:
[2024-07-22-1.zip](https://github.com/user-attachments/files/16339390/2024-07-22-1.zip)

**Comment by AquSG** [comment]
I've seen one other person talk to me about this error. I have no clue what to say. This is an extremely rare thing where some people just cannot enter the desert due to this.
The game simply is struggling to find the texture for the desert debris piles placed by the rubblemaker, and I don't know how anything I do could cause such a thing to happen. The best I can do is advise you to verify the integrity of your game files like the error window tells you to. If that doesn't work, then I have nothing else to say. Best of luck.

**Comment by beastup7up** [comment]
I feel it may be best to note that I also verified the game files, which still did not work.
